  # YAML Reference http://www.yaml.org/refcard.html
  continuum:
    discovery: sharedfs
    debug: true

  continuum-gateway:
    disableIam: true

  logging:
    level:
      com:
        kinotic: TRACE
      io:
        vertx: INFO

  spring:
    devtools:
      livereload:
        port: 35730
