  # YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true
  maxNumberOfCoresToUse: 2

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: DEBUG

spring:
  devtools:
    livereload:
      port: 35730
