  # YAML Reference http://www.yaml.org/refcard.html
  continuum:
    #discovery: zookeeper
    debug: true

  continuum-gateway:
    disableIam: false

  logging:
    level:
      com:
        kinotic: TRACE
      io:
        vertx: DEBUG

  spring:
    devtools:
      livereload:
        port: 35730
