  # YAML Reference http://www.yaml.org/refcard.html
  continuum:
    discovery: sharedfs
    debug: true

  #postgres
  continuum-iam:
    username: postgres
    password: pass79
    jdbcDriverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/continuum_iam
    secret: asdfasdfa0234amsmfalk24&asdf{}asf34as21

  # h2 db
#  continuum-iam:
#    jdbcUrl: jdbc:h2:~/.continuum/db/continuum-iam

  logging:
    level:
      com:
        kinotic: TRACE

    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
