name: Build and Publish to Maven

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - 'website/**'

jobs:
  gradle_build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_KEY_PASS

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Maven Central
        # We must -Psigning.gnupg.executable=gpg since setup-java provides gpg2 as gpg
        run: ./gradlew publish -Psigning.gnupg.executable=gpg -Psigning.gnupg.keyName="${{ secrets.GPG_KEY_ID }}" -Psigning.gnupg.passphrase="${{ secrets.GPG_KEY_PASS }}"
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN_PASSWORD }}

      - name: Publish to Docker Hub
        run: ./gradlew bootBuildImage --publishImage
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run E2E Tests
        run: |
          cd continuum-js/continuum-client
          ./gradlew pnpmInstall
          ./gradlew pnpmTest

      - name: Merge Test Results
        run: |
          mkdir -p allure-results
          cp -r */build/allure-results/* allure-results/
          cp -r continuum-js/*/allure-results/* allure-results/

      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
