name: Build and Deploy Continuum Website

on:
  push:
    branches:
      - develop
    paths:
      - 'website/continuum-vitepress/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: "./website/continuum-vitepress/pnpm-lock.yaml"

      - name: Install dependencies
        run: |
          cd website/continuum-vitepress
          pnpm install

      - name: Build Structures site
        run: |
          cd website/continuum-vitepress
          pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/continuum-vitepress/src/.vitepress/dist
          publish_branch: gh-pages
